### ISSUE TITLE
Fails to run with AttributeError when using py.test 2.9.*

### ISSUE THREAD

**Issue by rollokb** [tgoodlet/pytest-interactive#14]
Hey @tgoodlet project looks cool, but it fails to run with pytest 2.9.1.

An attribute error is raised here.

https://github.com/tgoodlet/pytest-interactive/blob/master/interactive/plugin.py#L92

Because `_obj` is no longer a member of the instance `node`.

**Comment by tgoodlet** [comment]
Thanks for reporting @rollokb. That's really weird because it seems to run fine on `3.0.1`.
It's also odd because I've been using latest `2.9.x` tagged releases right up until `3.0.x` and haven't had any problems.

So 2 questions:
- Is there any reason you need to stay on `2.9`? I'd rather not have to add version conditional code if possible.
- Can you provide me with a simple example that triggers the issue? I'm not having any luck :(

**Comment by tgoodlet** [comment]
@rollokb I actually double checked the `pytest` `2.9.x` sources just to be sure and if you look the [`PyObjMixin`](https://github.com/pytest-dev/pytest/blob/2.9.0/_pytest/python.py#L345) definitely still has that attribute.

If you can get me an example of where it fails I'll definitely take a look.
Thanks!

**Comment by tgoodlet** [comment]
@rollokb Didn't get any further feedback so I'm closing this for now.

**Comment by tgoodlet** [comment]
hah! I found this issue when trying to collect the `pytest` core test suite.

**Comment by tgoodlet** [comment]
@vodik can you try collecting the `pytest` core test suite with your change as part of #18?

**Comment by tgoodlet** [comment]
@rollokb heh after much much delay I believe this is finally fixed.
If you don't mind giving it a test that'd be 👍
