### ISSUE TITLE
pytest-interactive on python 2.6

### ISSUE THREAD

**Issue by cinvoke** [tgoodlet/pytest-interactive#9]
I'm trying to install this plugin on python 2.6 and ipython 1.2.1.
i had to take out the requirement in setup.py for ipython because it was trying to upgrade and needless to say, i want to keep the versions i have. 

 Any help is greatly appreciated.

http://dpaste.com/2XG00B8

Thank You

**Comment by tgoodlet** [comment]
Sorry about the slow response. I somehow missed this due to poorly setup email filters..
Currently, there is only support for python >= 2.7

The issue you are experiencing is that 2.6 does not support dictionary comprehension syntax. Unfortunately, there isn't much motivation to back port to 2.6 since it has been [EOL](https://mail.python.org/pipermail/python-dev/2013-September/128287.html) for a couple years now. I would highly recommend to move to 2.7 if you can.

**Comment by tgoodlet** [comment]
You are quite correct though the setup script needs to be adjusted to reflect this.

**Comment by tgoodlet** [comment]
Btw if you'd like to submit a PR with support for 2.6 I'll gladly accept it.
I'd start with the issue you found: http://stackoverflow.com/questions/1747817/create-a-dictionary-with-list-comprehension-in-python

**Comment by tgoodlet** [comment]
Got no PR so I'm closing this since 2.6 is deprecated.

**Comment by cinvoke** [comment]
Sorry just saw this. You're right, it may be time to let go of 2.6 ;)
